### ISSUE TITLE
Does not work in pods subdirectory

### ISSUE THREAD

**Issue by medokin** [KatalysatorAB/atom-ember-tabs#3] opened 2015-10-07 09:57 UTC
Any plan to address this issue?

![image](https://cloud.githubusercontent.com/assets/456683/10334435/7aa0bb90-6cea-11e5-9c83-8061a2671731.png)

**Comment by erkie** [comment] 2015-10-07 11:06
@medokin Oops. What exactly does your `podModulePrefix` contain?

**Comment by medokin** [comment] 2015-10-20 17:29
`podModulePrefix: 'webapp/pods',`

**Comment by DanChadwick** [comment] 2015-10-21 17:36
Same issue. Would love to see a fix. :)

**Comment by erkie** [comment] 2015-10-27 11:59
@medokin @DanChadwick can you try the `2.1.0` update and see if it fixes your issues? If it does, you can close this issue!

**Comment by DanChadwick** [comment] 2015-10-27 18:11
I tried 2.1.0 but I don't see a difference. I haven't gotten the podModulePrefix to work in ember (or atom, for that matter). Without any podModulePrefix (or with), I don't get the folder name in the tab name. ctrl-shift-m doesn't do anything (on Windows). I don't see any command in the advanced palette containing 'pod'.

I'm pretty new to ember and atom. I wish I could be of more help.

**Comment by DanChadwick** [comment] 2015-10-28 02:07
I'm confused. What I'm seeing is that atom, without atom-ember-tabs, distinguishes tabs when two have the same name, in the form "index.js - app\controllers". I don't see any change in behavior with the add-on enabled.

**Comment by erkie** [comment] 2015-11-02 10:09
@DanChadwick can you try installing `2.1.2` and see if it works? Close the issue if it does. Thanks!

**Comment by DanChadwick** [comment] 2015-11-02 23:14
I just updated and don't see the parent folder in the tab -- only the complete path when I hover. But them, I'm not sure that I have pods working at all. I tried both with and without a podModulePrefix.

**Comment by robneville73** [comment] 2015-11-06 20:19
+1 on 2.1.2 and not working as intended. I have no podModulePrefix defined as I don't use one. My pods structure works fine for the application so I know that part's right.

**Comment by erkie** [comment] 2015-11-12 11:09
@robneville73 @DanChadwick  I identified some places that could cause the project to not load properly. Can you update to `2.1.3` and check if it works?

**Comment by DanChadwick** [comment] 2015-11-12 11:59
I tried 2.1.3. At this point, I have no podModulePrefix. I created component with ember g --pods and opened both the test-item/component.js and test-item/template.hbs files. The tab does not have test-item in it.

**Comment by erkie** [comment] 2015-11-12 12:22
What does your .ember-cli file look like?

**Comment by robneville73** [comment] 2015-11-12 15:22
@erkie nope, doesn't work in 2.1.3 either.

Here's my .ember-cli file:

```
{
"disableAnalytics": false,
"usePods": true
}
```

**Comment by erkie** [comment] 2015-11-13 14:28
@robneville73 Can you open the console and see what message you are getting there? cmd+shift+i (or View > Developer > Toggle Developer Tools) and press the Console tab. You should see some messages with [ember-tabs] prefixed. That would help a lot!

**Comment by robneville73** [comment] 2015-11-13 14:34
2/Users/rneville/.atom/packages/ember-tabs/lib/ember-tabs.coffee:71
[ember-tabs] Did not detect ember project with pods enabled.
/Users/rneville/.atom/packages/ember-tabs/lib/ember-tabs.coffee:68
[ember-tabs] Detected Ember project. loft-mobile/pods.
/Users/rneville/.atom/packages/ember-tabs/lib/tab-watcher.coffee:13
[ember-tabs] Shimming tabs...

On Fri, Nov 13, 2015 at 9:28 AM, Erkie notifications@github.com wrote:

> @robneville73 https://github.com/robneville73 Can you open the console
> and see what message you are getting there? cmd+shift+i (or View >
> Developer > Toggle Developer Tools) and press the Console tab. You should
> see some messages with [ember-tabs] prefixed. That would help a lot!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KatalysatorAB/atom-ember-tabs/issues/3#issuecomment-156447006
> .

## 

Rob Neville
RetailArchitects

## (888) 891-4511 x801

For Support: (888) 891-4511 Option 1 or support@retailarchitects.com

**Comment by robneville73** [comment] 2015-11-16 15:41
2.1.5 still borked. :(

**Comment by erkie** [comment] 2015-11-16 15:42
@robneville73 can you send a screenshot of the console? View > Developer > Toggle Developer Tools

**Comment by robneville73** [comment] 2015-11-16 15:42
[ember-tabs] Everying read fine. Settings: true and loft-mobile/pods
/Users/rneville/.atom/packages/ember-tabs/lib/ember-tabs.coffee:68 [ember-tabs] Detected Ember project. loft-mobile/pods.
/Users/rneville/.atom/packages/ember-tabs/lib/tab-watcher.coffee:13 [ember-tabs] Shimming tabs...
3/Users/rneville/.atom/packages/ember-tabs/lib/tab-watcher.coffee:123 [ember-tabs] filePath: /Users/rneville/loft-mobile/app/pods/zipcode/edit/template.hbs was not an ember package path. Checked against: loft-mobile/pods

**Comment by robneville73** [comment] 2015-11-16 15:43
Looks like it's expecting pods to be at top level and not under the apps directory

**Comment by erkie** [comment] 2015-11-16 15:44
@robneville73 Hmm not sure, it seems from the console messages you sent that it's not updated properly. Can you restart atom and send a screenshot of the console this time, after you try to cmd+shift+m?

**Comment by robneville73** [comment] 2015-11-16 15:49
@erkie we're good. Just hadn't restarted Atom yet. It appears to be working now. Thanks!!

**Closed as completed** 2015-11-16 15:56 UTC
